### ISSUE TITLE
Add Support for other time units.

### ISSUE THREAD

**Issue by Craftizz** [Andre601/Formatter-Expansion#1]
Hello,

Please add support for other time units as the time output varies. Such in the case of auto rank where It outputs minutes instead of seconds. 

`%formatter_number_time_seconds_60% -> 1m`
`%formatter_number_time_minutes_1201% -> 20h 6m`
`%formatter_number_time_hours_25% -> 1d 1h`

Thank you!

**Comment by Andre601** [comment]
Has been added to 1.4.0.

New Placeholders:
- `%formatter_number_time_seconds_<number>` / `%formatter_number_time_secs_<number>%`
- `%formatter_number_time_minutes_<number>%` / `%formatter_number_time_mins_<number>%`
- `%formatter_number_time_hours_<number>%` / `%formatter_number_time_hrs_<number>%`
