### ISSUE TITLE
Feature Request?

### ISSUE THREAD

**Issue by DeOpping** [Andre601/Formatter-Expansion#8]
The reason I ask in the title is because it could already be a thing. If so I could not figure out how to do so and it does not appear to be listed in the README.

I'm here to ask about PlaceholderAPI support in this expansion's placeholders.
Something like.. `%formatter_text_replace_..._..._{{placeholder}}%`
Otherwise.. what's really the point? What would I use this for? I am currently looking to replace all "\<reset\>" with "" in a certain placeholder but it doesn't appear to allow that. If I wanted to replace something in a word or text, I'd just do it, why do I need the expansion? The only way I can use this is by inputting a placeholder.

If that is a feature, great, how can I utilize this?
If not, please add support for it, I don't know what else I'd use it for..

**Comment by Andre601** [comment]
It does support placeholders.
You just need to use the `{placeholder}` rather than `%plqceholder%` or `{{placeholder}}` (i.e. `{player_name}`)

**Comment by DeOpping** [comment]
Thank you!
